### PR TITLE
Make xcworkspace search work recursively

### PR DESCRIPTION
**Pull request by kattrali**
## Changes
- checks subdirectories for xcworkspaces
- notifies user which workspace is being monitored like: `Started xclistening to Alcatraz/Alcatraz.xcworkspace`
- notifies user when no workspaces are found like: `[!] No xcworkspace found in this directory (or any child directories)`

### CODE REVIEW

**Comment by supermarin** [comment]
@kattrali I'm in a big doubt of pressing this green button or not :smile:

**Comment by kattrali** [comment]
Haha, which part makes you worry? It starts listening to the first workspace found and notifies you which one was selected.

**Comment by supermarin** [comment]
it's not test driven

**Comment by supermarin** [comment]
I've rewrote a bit with tests, let me see if it's doable to do this quickly

**Comment by kattrali** [comment]
It kind of needs an acceptance suite to test well...

**Comment by supermarin** [comment]
Right, i've created one but never pushed because all the fixtures added up to 50mb repo.

Let me take a look with testing/merging this one first

**Comment by kattrali** [comment]
Maybe we don't need an actual xcworkspace as a fixture, but just the shell of one?

**Comment by supermarin** [comment]
I think the biggest mistake i've made was copy/pasting.
Git submodules would solve that issue :)

**Comment by kattrali** [comment]
Whoa. Maybe a little. :)

**Comment by supermarin** [comment]
alright i'll merge this and release so peoples can use the feature while we do useless testing :bee:

**Comment by kattrali** [comment]
lol I can take a stab at it. You're right that it needs tests.

**Comment by supermarin** [comment]
you can take a look here https://github.com/mneorr/xclisten/commit/7ef8eb49801094cf2045accfdf7e8a654acf3469, i've made that part pretty testable.

will try adding fixtures and see if we can use the real world examples rather than mocking `Dir.glob`

**Comment by kattrali** [comment]
I have an idea for how the fixtures should work, I'll push a sample to a new branch

**Pull request merged**
