### PR TITLE
add validation before running, and inform users that it's started

### PR DESCRIPTION
**Pull request by orta**
before

```
main
~ xclisten
/Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/lib/xclisten.rb:30:in `project_name': undefined method `split' for nil:NilClass (NoMethodError)
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/lib/xclisten.rb:13:in `initialize'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/bin/xclisten:32:in `new'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/bin/xclisten:32:in `block in <top (required)>'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/bin/xclisten:32:in `fork'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/gems/xclisten-0.0.3/bin/xclisten:32:in `<top (required)>'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/bin/xclisten:23:in `load'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/bin/xclisten:23:in `<main>'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/orta/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

after 

```
~/s/r/xclisten (master ⚡=) xclisten
Please run xclisten from a directory with an xcworkspace.
```

and 

```
~/s/i/energy (toolbar_polish ↩) xclisten
Started xclistening to Artsy Folio.xcworkspace
```

### CODE REVIEW

**Comment by supermarin** [comment]
@orta thanks for the pr!

I've wanted to take a different approach, search recursively for a workspace.
That has some advantages like:
- if you have a tree like below, you wouldn't be able to listen for file.h and .m if you've run `xclisten` from the `folder`

``` bash
code/
    file.h
    file.m
    folder/
        project.xcodeproj
        project.xcworkspace
```
- if you've run `xclisten` from a root folder like in ObjectiveSugar or some other pod, it'd just work

**Comment by supermarin** [comment]
We'll also support flag for -w / --workspace so you can specify one if there's many nested ones, but the closest one will be used

**Comment by orta** [comment]
that's fine, you could look at using `find -d 2 *.xcworkspace` to get back a list.

**Comment by supermarin** [comment]
:+1: 

In fact, a ruby way (Dir.glob) would be more preferred since we can mock it out in tests

**Comment by orta** [comment]
Then it's outside the scope of my PR.

I just added rudimentary validation.

**Comment by orta** [comment]
Closing, as this is a subset of:  https://github.com/mneorr/xclisten/pull/8

**Pull request closed without merging**
